{{- if and .Values.bridge.enabled .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "plumb.fullname" . }}
  labels:
    {{- include "plumb.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "plumb.bridgeSelectorLabels" . | nindent 6 }}
{{- end }}
