/**
 * The design the offline demo runs against: a three-tier pricing screen,
 * shaped exactly as `plumb_node` returns it for a real Figma frame — token
 * table, flat `el → node` map, `$cN`/`$tN`/`$rN`/`$sN` refs and all.
 *
 * It is a `.ts` module rather than a checked-in JSON blob so `satisfies
 * PdsDocument` typechecks it on every build: a fixture that drifts out of the
 * schema fails CI instead of silently making the demo lie. `npm run demo --
 * --pds` prints it as the JSON an agent would actually receive.
 */
import type { PdsDocument } from "../pds";

const TOKENS = {
  color: {
    $c0: "#0b1120", // page background
    $c1: "#141c31", // card surface
    $c2: "#f8fafc", // primary text
    $c3: "#94a3b8", // muted text
    $c4: "#6366f1", // brand
    $c5: "#1e293b", // hairline
    $c6: "#ffffff", // on-brand text
    $c7: "#c7d2fe", // brand tint
  },
  text: {
    $t0: "600 12px/1.4 Inter",
    $t1: "700 48px/1.1 Inter",
    $t2: "400 18px/1.6 Inter",
    $t3: "600 20px/1.3 Inter",
    $t4: "700 40px/1.1 Inter",
    $t5: "400 15px/1.5 Inter",
    $t6: "600 15px/1.2 Inter",
    $t7: "400 13px/1.5 Inter",
  },
  radius: { $r0: 20, $r1: 12, $r2: "full" as const },
  shadow: {
    $s0: "0px 8px 24px rgba(0, 0, 0, 0.24)",
    $s1: "0px 16px 48px rgba(99, 102, 241, 0.35)",
  },
  layout: {
    $l0: { flow: "col" as const, gap: 12, pad: [0, 0, 0, 0] as [number, number, number, number] },
    $l1: {
      flow: "row" as const,
      gap: 0,
      pad: [12, 20, 12, 20] as [number, number, number, number],
      justify: "center",
      align: "center",
    },
  },
};

/** One feature row inside a plan card — the same shape repeats nine times. */
function feature(el: string, id: string, chars: string): PdsDocument["nodes"][string] {
  return {
    id,
    el,
    type: "text",
    name: "Feature",
    box: { w: 232, h: 22 },
    text: "$t5",
    fill: "$c3",
    chars,
    sizing: { w: "fill", h: "hug" },
  };
}

export const PRICING_PDS: PdsDocument = {
  schemaVersion: "1.0.0",
  file: { name: "Acme — Marketing Site", version: "2481" },
  root: "pricing",
  tokens: TOKENS,
  nodes: {
    pricing: {
      id: "12:100",
      el: "pricing",
      type: "frame",
      name: "Pricing",
      box: { w: 1152, h: 720 },
      layout: { flow: "col", gap: 48, pad: [80, 96, 80, 96], align: "center" },
      fill: "$c0",
      children: ["header", "plans", "footnote"],
    },

    header: {
      id: "12:101",
      el: "header",
      type: "frame",
      name: "Header",
      box: { w: 640, h: 148 },
      layout: "$l0",
      inheritedFill: "$c0",
      children: ["eyebrow", "title", "subtitle"],
    },
    eyebrow: {
      id: "12:102",
      el: "eyebrow",
      type: "text",
      name: "Eyebrow",
      box: { w: 640, h: 17 },
      text: "$t0",
      fill: "$c4",
      chars: "PRICING",
      textCase: "UPPER",
      sizing: { w: "fill", h: "hug" },
    },
    title: {
      id: "12:103",
      el: "title",
      type: "text",
      name: "Title",
      box: { w: 640, h: 53 },
      text: "$t1",
      fill: "$c2",
      chars: "Simple, honest pricing",
      sizing: { w: "fill", h: "hug" },
    },
    subtitle: {
      id: "12:104",
      el: "subtitle",
      type: "text",
      name: "Subtitle",
      box: { w: 640, h: 58 },
      text: "$t2",
      fill: "$c3",
      chars: "Every plan includes the full design-to-code loop. Upgrade when your team does.",
      sizing: { w: "fill", h: "hug" },
    },

    plans: {
      id: "12:110",
      el: "plans",
      type: "frame",
      name: "Plans",
      box: { w: 960, h: 420 },
      layout: { flow: "row", gap: 24, pad: [0, 0, 0, 0], align: "stretch" },
      inheritedFill: "$c0",
      children: ["card-starter", "card-pro", "card-team"],
    },

    // ── Starter ────────────────────────────────────────────────────────────
    "card-starter": {
      id: "12:120",
      el: "card-starter",
      type: "frame",
      name: "Starter plan",
      box: { w: 304, h: 420 },
      layout: { flow: "col", gap: 24, pad: [32, 32, 32, 32] },
      fill: "$c1",
      radius: "$r0",
      shadow: "$s0",
      stroke: "$c5",
      strokeW: 1,
      strokeAlign: "inside",
      grow: 1,
      children: [
        "starter-name",
        "starter-price",
        "starter-rule",
        "starter-features",
        "starter-cta",
      ],
    },
    "starter-name": {
      id: "12:121",
      el: "starter-name",
      type: "text",
      name: "Plan name",
      box: { w: 240, h: 26 },
      text: "$t3",
      fill: "$c2",
      chars: "Starter",
      sizing: { w: "fill", h: "hug" },
    },
    "starter-price": {
      id: "12:122",
      el: "starter-price",
      type: "text",
      name: "Price",
      box: { w: 240, h: 44 },
      text: "$t4",
      fill: "$c2",
      chars: "$0",
      sizing: { w: "fill", h: "hug" },
    },
    "starter-rule": {
      id: "12:123",
      el: "starter-rule",
      type: "rect",
      name: "Rule",
      box: { w: 240, h: 1 },
      fill: "$c5",
      sizing: { w: "fill", h: "fixed" },
    },
    "starter-features": {
      id: "12:124",
      el: "starter-features",
      type: "frame",
      name: "Features",
      box: { w: 240, h: 90 },
      layout: "$l0",
      inheritedFill: "$c1",
      grow: 1,
      children: ["starter-f1", "starter-f2", "starter-f3"],
    },
    "starter-f1": feature("starter-f1", "12:125", "1 project"),
    "starter-f2": feature("starter-f2", "12:126", "Community support"),
    "starter-f3": feature("starter-f3", "12:127", "1 GB asset storage"),
    "starter-cta": {
      id: "12:128",
      el: "starter-cta",
      type: "frame",
      name: "Secondary CTA",
      box: { w: 240, h: 46 },
      layout: "$l1",
      fill: "$c1",
      stroke: "$c4",
      strokeW: 1,
      strokeAlign: "inside",
      radius: "$r2",
      sizing: { w: "fill", h: "fixed" },
      children: ["starter-cta-label"],
    },
    "starter-cta-label": {
      id: "12:129",
      el: "starter-cta-label",
      type: "text",
      name: "CTA label",
      box: { w: 88, h: 18 },
      text: "$t6",
      fill: "$c7",
      chars: "Start free",
    },

    // ── Pro (the highlighted tier) ─────────────────────────────────────────
    "card-pro": {
      id: "12:140",
      el: "card-pro",
      type: "frame",
      name: "Pro plan",
      box: { w: 304, h: 420 },
      layout: { flow: "col", gap: 24, pad: [32, 32, 32, 32] },
      fills: [
        { type: "color", color: "#141c31" },
        {
          type: "linear-gradient",
          angle: 160,
          stops: [
            { at: 0, color: "#6366f133" },
            { at: 1, color: "#6366f100" },
          ],
        },
      ],
      radius: "$r0",
      shadow: "$s1",
      stroke: "$c4",
      strokeW: 1,
      strokeAlign: "inside",
      grow: 1,
      children: ["pro-badge", "pro-name", "pro-price", "pro-rule", "pro-features", "pro-cta"],
    },
    "pro-badge": {
      id: "12:141",
      el: "pro-badge",
      type: "frame",
      name: "Badge",
      box: { w: 92, h: 24 },
      layout: { flow: "row", gap: 0, pad: [4, 10, 4, 10], justify: "center", align: "center" },
      fill: "$c4",
      radius: "$r2",
      selfAlign: "min",
      children: ["pro-badge-label"],
    },
    "pro-badge-label": {
      id: "12:142",
      el: "pro-badge-label",
      type: "text",
      name: "Badge label",
      box: { w: 72, h: 17 },
      text: "$t0",
      fill: "$c6",
      chars: "MOST POPULAR",
      textCase: "UPPER",
    },
    "pro-name": {
      id: "12:143",
      el: "pro-name",
      type: "text",
      name: "Plan name",
      box: { w: 240, h: 26 },
      text: "$t3",
      fill: "$c2",
      chars: "Pro",
      sizing: { w: "fill", h: "hug" },
    },
    "pro-price": {
      id: "12:144",
      el: "pro-price",
      type: "text",
      name: "Price",
      box: { w: 240, h: 44 },
      text: "$t4",
      fill: "$c2",
      chars: "$24",
      sizing: { w: "fill", h: "hug" },
    },
    "pro-rule": {
      id: "12:145",
      el: "pro-rule",
      type: "rect",
      name: "Rule",
      box: { w: 240, h: 1 },
      fill: "$c5",
      sizing: { w: "fill", h: "fixed" },
    },
    "pro-features": {
      id: "12:146",
      el: "pro-features",
      type: "frame",
      name: "Features",
      box: { w: 240, h: 90 },
      layout: "$l0",
      grow: 1,
      children: ["pro-f1", "pro-f2", "pro-f3"],
    },
    "pro-f1": feature("pro-f1", "12:147", "Unlimited projects"),
    "pro-f2": feature("pro-f2", "12:148", "Self-healing fit loop"),
    "pro-f3": feature("pro-f3", "12:149", "50 GB asset storage"),
    "pro-cta": {
      id: "12:150",
      el: "pro-cta",
      type: "frame",
      name: "Primary CTA",
      box: { w: 240, h: 46 },
      layout: "$l1",
      fill: "$c4",
      radius: "$r2",
      shadow: "$s1",
      sizing: { w: "fill", h: "fixed" },
      children: ["pro-cta-label"],
    },
    "pro-cta-label": {
      id: "12:151",
      el: "pro-cta-label",
      type: "text",
      name: "CTA label",
      box: { w: 76, h: 18 },
      text: "$t6",
      fill: "$c6",
      chars: "Choose Pro",
    },

    // ── Team ───────────────────────────────────────────────────────────────
    "card-team": {
      id: "12:160",
      el: "card-team",
      type: "frame",
      name: "Team plan",
      box: { w: 304, h: 420 },
      layout: { flow: "col", gap: 24, pad: [32, 32, 32, 32] },
      fill: "$c1",
      radius: "$r0",
      shadow: "$s0",
      stroke: "$c5",
      strokeW: 1,
      strokeAlign: "inside",
      grow: 1,
      children: ["team-name", "team-price", "team-rule", "team-features", "team-cta"],
    },
    "team-name": {
      id: "12:161",
      el: "team-name",
      type: "text",
      name: "Plan name",
      box: { w: 240, h: 26 },
      text: "$t3",
      fill: "$c2",
      chars: "Team",
      sizing: { w: "fill", h: "hug" },
    },
    "team-price": {
      id: "12:162",
      el: "team-price",
      type: "text",
      name: "Price",
      box: { w: 240, h: 44 },
      text: "$t4",
      fill: "$c2",
      chars: "$96",
      sizing: { w: "fill", h: "hug" },
    },
    "team-rule": {
      id: "12:163",
      el: "team-rule",
      type: "rect",
      name: "Rule",
      box: { w: 240, h: 1 },
      fill: "$c5",
      sizing: { w: "fill", h: "fixed" },
    },
    "team-features": {
      id: "12:164",
      el: "team-features",
      type: "frame",
      name: "Features",
      box: { w: 240, h: 90 },
      layout: "$l0",
      grow: 1,
      children: ["team-f1", "team-f2", "team-f3"],
    },
    "team-f1": feature("team-f1", "12:165", "Everything in Pro"),
    "team-f2": feature("team-f2", "12:166", "Shared design graph"),
    "team-f3": feature("team-f3", "12:167", "SSO and audit log"),
    "team-cta": {
      id: "12:168",
      el: "team-cta",
      type: "frame",
      name: "Secondary CTA",
      box: { w: 240, h: 46 },
      layout: "$l1",
      fill: "$c1",
      stroke: "$c4",
      strokeW: 1,
      strokeAlign: "inside",
      radius: "$r2",
      sizing: { w: "fill", h: "fixed" },
      children: ["team-cta-label"],
    },
    "team-cta-label": {
      id: "12:169",
      el: "team-cta-label",
      type: "text",
      name: "CTA label",
      box: { w: 92, h: 18 },
      text: "$t6",
      fill: "$c7",
      chars: "Talk to sales",
    },

    footnote: {
      id: "12:180",
      el: "footnote",
      type: "text",
      name: "Footnote",
      box: { w: 640, h: 20 },
      text: "$t7",
      fill: "$c3",
      chars: "Prices in USD. Cancel any time.",
      sizing: { w: "fill", h: "hug" },
    },
  },
  meta: { nodeCount: 38, estTokens: 1840, depthUsed: 4 },
  next:
    "Build each `el` and stamp data-plumb-id=\"<el>\" on it, then call plumb_fit " +
    "with the rendered boxes + computed styles to score the match.",
} satisfies PdsDocument;
